name: pbl_kelompok6_sertifikasipelatihan_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/training.jpg
  - assets/ai_training.jpg
  - assets/cyber.jpg
  - assets/data_science.jpg
  - assets/game.jpg
  - assets/ai2.jpg
  - assets/data_analyst.jpg