name: pbl_kelompok6_sertifikasipelatihan_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
<<<<<<< HEAD
  file_picker: ^8.1.4
=======
  file_picker: ^5.2.0
>>>>>>> c6bb396a77ee5303e08d5b43c926946fe88f6fbd
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/training.jpg
  - assets/ai_training.jpg
  - assets/cyber.jpg
  - assets/data_science.jpg
  - assets/game.jpg
  - assets/ai2.jpg
  - assets/data_analyst.jpg
